### ISSUE TITLE
mirv_block_commands doesn't work on GoldSrc ?

### ISSUE THREAD

**Issue by xerus6** [ripieces/advancedfx#731] opened 2021-11-17 06:43 UTC
Is it not working or am I missing something?

**Comment by dtugend** [comment] 2021-11-17 06:49
The command is currently only available in AfxHookSource / CS:GO:
- https://github.com/advancedfx/advancedfx/wiki/Source%3ACommands
- https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ACommands

I am not sure it would make sense that way in GoldSrc.

**Comment by dtugend** [comment] 2021-11-17 09:28
If you want to block certain commands in GoldSrc you can use:
HLAE Menu -> Tools -> GoldSrc -> Demo Tools
and tick [x] DemoCleanUp there

**Comment by xerus6** [comment] 2021-11-17 19:59
> If you want to block certain commands in GoldSrc you can use: HLAE Menu -> Tools -> GoldSrc -> Demo Tools and tick [x] DemoCleanUp there

Is there any way I can stop receiving this while playing a demo, without removing the -demoedit launch option? 

![image](https://user-images.githubusercontent.com/45909555/142273220-9486ec64-5a25-4579-8510-31fe8ab7347a.png)

**Comment by dtugend** [comment] 2021-11-18 08:20
Not 100% sure, but it should be the "Remove the AMX text" at the end of this page:
https://style-productions.net/?page=read_guide&id=52

**Comment by xerus6** [comment] 2021-11-22 10:06
> Not 100% sure, but it should be the "Remove the AMX text" at the end of this page: https://style-productions.net/?page=read_guide&id=52

I've tried it before, it only removes the amx text from the hud. I don't think there is a way to block these type of messages unless I remove the -demoedit option.

**Comment by dtugend** [comment] 2021-11-22 15:24
Can you screenshot the text in-game, I think I remember someone with a similar problem and there was a solution I think.

If it's what I think try

```
hud_centerid 20
```

or

```
hud_centerid -20
```

**Comment by dtugend** [comment] 2021-11-22 15:33
Hi I just tested following the instructions correctly (ending up with a new `C:\Program Files (x86)\Steam\steamapps\common\Half-Life\cstrike\resource\TrackerScheme.res`) and it successfully removes the colored text for me (don't forget to restart CS 1.6).

Maybe you mean some other text, e.g. the one of hud_centerid, in that case try `hud_centerid 200`.

If none of these solve it, please screenshot the text.

Edit: I meant hud_centerid 200 not 20.

**Comment by dtugend** [comment] 2021-11-22 15:59
I juste realized I might have misunderstood you, I thought the problem is in-game, do you only refer to the messages popping up in the demoedit event list? If yes, then I don't know an officialy way to get permanently rid of them using the "Remove" button without breaking / saving the demo.

**Comment by xerus6** [comment] 2021-11-26 10:47
I'ill explain what happens exactly, I wan't to record a campath, but when I open a demo and after it finishes loading those messages starts to pop up just like you saw on the screenshot, and my fps drops to like 20 fps for a while and then my the game crashes, this only happens when I open a demo using the -demoedit launch option, because it's the only way I know to record a campath. I've tried spamming the 'remove' button with my enter key but it doesn't seem to be solving the problem, the game keeps crashing after I open the demo.

**Comment by xerus6** [comment] 2021-11-26 10:52
The messages are the speed velocity updates of my character movement that were recorded in the demo, I think the velocity is part of the hud, but removing the hud didn't help either. The demo was recorded on a hns mod server.

**Comment by dtugend** [comment] 2021-11-26 16:41
HLAE supports mirv_campath these days, it doesn't need demoedit:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_campath

Works the same like in CS:GO.

**Comment by xerus6** [comment] 2021-11-27 07:39
Oh, Thank you so much sir!

**Comment by dtugend** [comment] 2021-11-30 20:07
do we want to close this or not? 3 people seem to be unsure, including me, lol.

**Comment by xerus6** [comment] 2023-05-01 15:24
Sorry for the late response lol, you can close this issue if you want, since [this](https://github.com/advancedfx/advancedfx/issues/731#issuecomment-980121155) solved the issue that I had.

**Closed as completed** 2023-05-01 17:39 UTC
Labels: enhancement
