### ISSUE TITLE
Error - AfxHookSource2

### ISSUE THREAD

**Issue by LANGEw0w** [ripieces/advancedfx#987] opened 2024-10-03 07:11 UTC
I can't launch Counter-Strike 2 through HLAE.

1. I have downloaded the newest version of HLAE (2.171.1.0)
2. Enter Custom loader
3. Add CS2 (C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe)
4. Add commandlines (-steam -insecure +sv_lan 1 -console -novid -console -sw -w 1920 -h 1080)
5. Add DLL by browsing HLAE folder>x64>AfxHookSource2.dll
6. Hit OK and game launches but crashes after following errors https://imgur.com/a/lbbLPOQ

Is this due to the new update? Or am I doing something wrong?

**Comment by dtugend** [comment] 2024-10-03 07:30
yes it#s due to update, issue is duplicate of #986 thus closing.

**Closed as completed by dtugend** 2024-10-03 07:30 UTC
Labels: bug
