### ISSUE TITLE
HLAE can't open demo

### ISSUE THREAD

**Issue by Wrabberg** [ripieces/advancedfx#772] opened 2022-06-07 16:04 UTC
Some shit happens whenever I was trying to open demo on de_Cache. After loading the map for a short time, HLAE just closes without any errors. Menu loading bar had never loaded to the end
https://github.com/advancedfx/advancedfx/discussions/categories/q-a

**Comment by dtugend** [comment] 2022-06-07 18:06
Changing mat_queue_mode can cause demo crashes, make sure it's set to the same value in your cfg/video.txt as in-game.

If in doubt use / enable the mmcfg folder feaature in File -> Lanch CS:GO and set a new empty folder on your desktop for it using the browse button next to it.

**Comment by Wrabberg** [comment] 2022-06-07 20:44
"mat_queue_mode -1" just as in-game. New empty folder also doesn't help. After crash opens empty window with "Engine error" heading

**Comment by dtugend** [comment] 2022-06-08 06:14
1. Please check if you have an "addon" or "addons" folder in your CS:GO's csgo folder, if yes please reanme or delete it.
2. Are there any other error messages when launching HLAE for CS:GO?
3. What's the exact error message?
4. Does the error happen as well with the same demo when not using HLAE? (Some demos are just broken and it's a CS:GO problem.)

**Comment by Wrabberg** [comment] 2022-06-08 12:13
1. There aren't any "addon" or "addons" folders in my csgo folder
2. There aren't any other error messages
3. Error window just empty. Only "Engine error" message on the top of that window
4. This demo opens correctly when I'm trying to open it in vanilla CS:GO

**Comment by dtugend** [comment] 2022-06-08 14:05
Usually this error indicates a problem with mat_queue_mode being changed from 0 to s.th. else.
(The correct video.txt file is in Steam folder\\userdata\\steam_account_id\\730\\cfg, but since you said you tried the mmcfg folder feature already, it's some other problem I maybe).

1. Compare the path you set in HLAE to csgo.exe with the one you get when you right click CS:GO in steam library -> properties -> local files tab -> browse local files button.
2. Please provide a copy of the demo to us and also all HLAE commands used when using it (if any) and any other instructions that might be helpful for reproducing the problem.

**Comment by Wrabberg** [comment] 2022-06-08 15:08
The path in HLAE is the same
That demo: [2 3 noscope.zip](https://github.com/advancedfx/advancedfx/files/8862879/2.3.noscope.zip)
HLAE commands: -steam -insecure +sv_lan 1 -console -game csgo -windowed -disable_d3d9ex

**Comment by dtugend** [comment] 2022-06-08 15:25
![image](https://user-images.githubusercontent.com/3610128/172654278-685d2331-bbbb-480c-bd7f-f97fadd5cd61.png)
Sadly the demo works just fine for me.

1. Consider if it could be caused by buggy game overlays, we had problems in the past with buggy NVIDA Geforce driver overlays crashing e.g..
2. Make sure you are really using the latest HLAE version, if possible.
3. Also make sure to verify the game cache (in CS:GO Propertiers -> Local Files tab -> verify game cache button) first.
4. It it still crashes you can check `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive` for an .mdmp file or `C:\Program Files (x86)\Steam\dumps` for a .dmp file **from the time** when csgo crashed for you (I only need one or two, you can use e.g. 7-zip.org to compress them. Those are crash dumps that contain debugging information. Please *do NOT upload them publically*, because they may contain sensitive information, instead send an email to contact@advancedfx.org and mention this issue (so I know what it is for). If it's easier for you we can also try to meet on the HLAE Discord (linked on support page), I am dtugend#2090 there.

**Comment by dtugend** [comment] 2022-06-08 21:33
It was probably caused by outdated side-by-side DLLs insisde the HLAE folder probably.
(old ones from unzipping HLAE again and again into same folder)

**Comment by dtugend** [comment] 2022-06-09 06:55
since we solved it by unzipping HLAE into a clean folder, I'll close this issue until / unless further problems pop up

**Closed as completed by dtugend** 2022-06-09 06:55 UTC
Labels: question
