### ISSUE TITLE
mirv_pov crash out game

### ISSUE THREAD

**Issue by Tycacto** [ripieces/advancedfx#739] opened 2021-12-11 19:42 UTC
(Please search existing **open and closed** issues first to verify this is a new bug report.)
hi admin maybe my question is a bit confusing because i use google translate to talk , to the main problem , when i use mirv_pov my game immediately exits and when i go back in and do it again it's still the same , All demos are expected admin can fix the error soon so I can make clips, thanks a lot.

**Comment by dtugend** [comment] 2021-12-11 19:54
Hi, we are aware, this seems to be a duplicate of #738

**Comment by Tycacto** [comment] 2021-12-11 20:07
that's right, I've checked his error and I have the same problem, hope admin can fix it as soon as possible, thanks admin.

**Comment by kaidos1** [comment] 2021-12-11 20:22
For me now works idk why. I just veryfied the game.

**Comment by Tycacto** [comment] 2021-12-11 20:35
i veryfied the game , but it's still the same. :(

**Comment by dtugend** [comment] 2021-12-11 21:14
https://github.com/advancedfx/advancedfx/releases/tag/v2.124.5

**Comment by dtugend** [comment] 2021-12-11 22:31
https://github.com/advancedfx/advancedfx/releases/tag/v2.124.6

**Closed as completed by dtugend** 2021-12-11 22:31 UTC
Labels: bug

**Comment by Tycacto** [comment] 2021-12-11 23:07
it worked, i can only say thank you so much.
