### ISSUE TITLE
mirv_listentities isplayer=1unavailable

### ISSUE THREAD

**Issue by wen47810** [ripieces/advancedfx#819] opened 2023-01-02 17:25 UTC
After I start csgo and enter a video input mirv_listentities isplayer=1, the following will appear 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/121820061/210262852-96329186-9625-4e9c-af41-067a5550b98a.png">

**Comment by wen47810** [comment] 2023-01-02 17:26
What I need is the player xuid, but in fact he doesn't appear

**Comment by dtugend** [comment] 2023-01-02 18:04
Enter
`con_filter_enable 0`
in console to see if that solves the problem.

**Comment by dtugend** [comment] 2023-01-02 18:06
If the above doesn't solve the problem please provide the outputs of
```
version
```
and
```
__mirv_info
```

**Comment by wen47810** [comment] 2023-01-03 01:17
Enter con_filter_enable 0 has no effect or feedback
<img width="640" alt="Counter-strike  Global Offensive Screenshot 2023 01 03 - 09 14 10 82" src="https://user-images.githubusercontent.com/121820061/210289123-871e5e61-a8df-487a-9682-e66ec12b9655.png">
<img width="640" alt="Counter-strike  Global Offensive Screenshot 2023 01 03 - 09 17 34 64" src="https://user-images.githubusercontent.com/121820061/210289124-2db36cc2-6d0f-4a7e-a6d6-2fd4985ea2b2.png">

**Comment by dtugend** [comment] 2023-01-03 07:05
1. Do this with HLAE:
```
mirv_block_commands print
```
and provide the output you are getting here please.

2. Do this **without** HLAE being used, directly in the game, to see if ithe problem is HLAE related or not:
```
version
```

Because normally the version output should look like this:
```
] version
Protocol version 13850 [1539/1539]
Exe version 1.38.5.0 (csgo)
Exe build: 08:58:10 Dec 13 2022 (8802) (730)
Windows version 6.2
Steam beta name: 
```

Maybe it's some other non-standard chat filter being broken or a broken font, dunno yet.

Edit:
Additionally it might help if you verify the cache of the game.
Also if you have an addons folder in the csgo subfolder, please rename or delete it.

**Comment by dtugend** [comment] 2023-01-03 08:11
Additonally, if possible for you, it might help us, in case you can provide the demo file as a download.
Edit: if you don't want to share it publically send the download to contact@advancedfx.org and mention this issue number (819) in the email.

**Comment by wen47810** [comment] 2023-01-03 21:08
This one doesn't do anything
<img width="640" alt="Counter-strike  Global Offensive Screenshot 2023 01 04 - 05 02 06 61" src="https://user-images.githubusercontent.com/121820061/210441701-560f9e44-8b0f-47f4-8425-dd50aec80839.png">

**Comment by wen47810** [comment] 2023-01-03 21:09
<img width="640" alt="Counter-strike  Global Offensive Screenshot 2023 01 04 - 05 07 02 41" src="https://user-images.githubusercontent.com/121820061/210441816-acf6c4b3-66e0-4453-bf05-1ba9cf3b4c09.png">

**Comment by dtugend** [comment] 2023-01-04 17:24
- Additionally it might help if you verify the cache of the game.

- Also if you have an addons folder in the csgo subfolder, please rename or delete it.

- If possible for you, it might help us, in case you can provide the demo file as a download.  
If you don't want to share it publically send the download to [contact@advancedfx.org](mailto:contact@advancedfx.org) and mention this issue number (819) in the email.

**Comment by dtugend** [comment] 2023-01-17 15:27
(Closing until further information / feedback is available.)

**Closed as completed by dtugend** 2023-01-17 15:27 UTC
Labels: question
